Repository basketini-jones/lootdeck, pull requests merged in 2021-12, with the labels that each got.

#364 Animted items compatinbility
  main.lua
  resources/gfx/items/collectibles/animated/lootDeckAnimated.anm2
  resources/gfx/items/collectibles/animated/lootDeckAnimated.png
  resources/gfx/items/collectibles/animated/playerCardAnimated.anm2
  resources/gfx/items/collectibles/animated/playerCardAnimated.png
Labels: enhancement

#363 Make all lootcard passives hidden
  content/items.xml
Labels: bug

#369 Add collection page icons
  content/costumes2.xml
  content/gfx/death items.anm2
  content/gfx/death items.png
  content/items.xml
Labels: enhancement

#370 Bloody Penny effect only triggers on vulnerable enemies
  items/bloodyPenny.lua
Labels: bug

#371 Player Card lootcard spawn can no longer be holo
  items/playerCard.lua
Labels: enhancement

#375 Cain's Eye now accounts for items like Map, Compass, and Blue Map
  items/cainsEye.lua
  main.lua
Labels: bug

#381 Stops bloody penny from spawning lootcards when killing fireplace
  items/bloodyPenny.lua
Labels: bug

#384 Updated Glyph of Balance algorithm
  helpers/pickups.lua
Labels: bug

#376 GET_CARD PercentageChance now uses rng arg
  cards/aSack.lua
  cards/ansuz.lua
  cards/blackPill.lua
  cards/blackRune.lua
  cards/blankRune.lua
  cards/bluePill.lua
  cards/bomb.lua
  cards/dagaz.lua
  cards/goldBomb.lua
  cards/jera.lua
  cards/judgement.lua
  cards/perthro.lua
  cards/purplePill.lua
  cards/questionCard.lua
  cards/redPill.lua
  cards/temperance.lua
  cards/theDevil.lua
  cards/theEmperor.lua
  cards/theHermit.lua
  cards/theHighPriestess.lua
  cards/theMoon.lua
  cards/theStars.lua
  cards/theTower.lua
  cards/wheelOfFortune.lua
  cards/whitePill.lua
  cards/whiteSpottedPill.lua
  cards/yellowPill.lua
  entityVariants/creditCardBaby.lua
  entityVariants/devilHand.lua
  entityVariants/justiceHaunt.lua
  entityVariants/lostSoulBaby.lua
  entityVariants/lostSoulLove.lua
  helpers/entities.lua
  helpers/lootcards.lua
  helpers/pickups.lua
  helpers/utils.lua
  items/bloodyPenny.lua
  items/cainsEye.lua
  items/lootDeck.lua
  items/playerCard.lua
  items/purpleHeart.lua
  items/swallowedPenny.lua
  main.lua
Labels: bug

#411 Spawns The Devil items at least one grid space away from players and makes sure the items are actually randomized
  cards/theDevil.lua
  cards/theHermit.lua
Labels: bug

#426 Swapped around hanged man effect
  cards/theHangedMan.lua
Labels: enhancement

#425 Add poof, fixed pageant boy bug with Poker Chip
  items/pokerChip.lua
Labels: bug, enhancement

#424 Charged Pennies only play sound if needed
  entityVariants/chargedPenny.lua
  entityVariants/doubleChargedPenny.lua
  helpers/players.lua
Labels: bug

#423 Swallowed Penny rework
  items/swallowedPenny.lua
Labels: enhancement

#427 Two of Diamonds familiar does Midas Freeze on enemy contact
  entityVariants/diamondBaby.lua
Labels: enhancement

#428 Updated mimic charges for Jera, Counterfeit Penny, and Swallowed Penny
  content/pocketitems.xml
Labels: enhancement

#430 Fix DSN (u know what it is)
  entityVariants/doubleStickyNickel.lua
Labels: bug

#421 Counterfeit Penny rework
  helpers/pickups.lua
  helpers/utils.lua
  items/brokenAnkh.lua
  items/counterfeitPenny.lua
  resources/gfx/characters/costumes/costume_hangedMan.png
  resources/gfx/characters/costumes_shadow/costume_hangedMan.png
  resources/gfx/characters/hangedMan.anm2
  resources/sfx/counterfeit penny.wav
  sounds/registry.lua
Labels: enhancement

#429 updated descriptions
  cards/brokenAnkh.lua
  cards/counterfeitPenny.lua
  cards/death.lua
  cards/swallowedPenny.lua
  cards/theHangedMan.lua
  cards/twoOfDiamonds.lua
  items/counterfeitPenny.lua
  items/swallowedPenny.lua
Labels: documentation

#433 Gave sun a 5 second timer + Added player inventory check on every update for Sun
  cards/theSun.lua
  resources/gfx/coloroverlays/white_overlay.png
Labels: enhancement
