Repository basketini-jones/lootdeck, pull requests merged in 2021-11, with the labels that each got.

#207 Return Tape Worm chance to 10-25%
  items/tapeWorm.lua
Labels: bug

#208 Store lootcard chance
  helper_functions.lua
  main.lua
  modConfigMenu.lua
Labels: bug

#210 hiero persists between rooms, better mantle damage detection
  cards/theHierophant.lua
  helper_functions.lua
  items/guppysHairball.lua
Labels: bug, enhancement

#267 add gold particles and sfx to gold bomb
  cards/goldBomb.lua
  main.lua
Labels: enhancement

#271 This removes the old HUD system and revamps the chance cards
  cards/blackPill.lua
  cards/blackRune.lua
  cards/blankRune.lua
  cards/bluePill.lua
  cards/dagaz.lua
  cards/dime.lua
  cards/fourCents.lua
  cards/lilBattery.lua
  cards/megaBattery.lua
  cards/nickel.lua
  cards/penny.lua
  cards/purplePill.lua
  cards/redPill.lua
  cards/soulHeart.lua
  cards/threeCents.lua
  cards/twoCents.lua
  cards/wheelOfFortune.lua
  cards/whitePill.lua
  cards/whiteSpottedPill.lua
  cards/yellowPill.lua
  helper_functions.lua
  items/brokenAnkh.lua
  main.lua
Labels: enhancement

#272 removed illegal parents list from black pill
  cards/blackPill.lua
Labels: chore

#278 add black poof to spawnie of black rune portals
  cards/blackRune.lua
Labels: enhancement

#275 AAA Battery now filters out actives
  items/aaaBattery.lua
Labels: bug

#280 add charge visual to purple pill
  cards/purplePill.lua
  helper_functions.lua
Labels: enhancement

#279 Add Gimme the Loot challenge
  cards/aSack.lua
  cards/blackRune.lua
  cards/blankRune.lua
  cards/bluePill.lua
  cards/chargedPenny.lua
  cards/dime.lua
  cards/fourCents.lua
  cards/holyCard.lua
  cards/judgement.lua
  cards/lilBattery.lua
  cards/megaBattery.lua
  cards/nickel.lua
  cards/penny.lua
  cards/perthro.lua
  cards/temperance.lua
  cards/theDevil.lua
  cards/theHermit.lua
  cards/theStars.lua
  cards/threeCents.lua
  cards/twoCents.lua
  cards/wheelOfFortune.lua
  challenges/gimmeTheLoot.lua
  challenges/registry.lua
  content/challenges.xml
  entityVariants/creditCardBaby.lua
  entityVariants/devilHand.lua
  entityVariants/doubleGoldenPenny.lua
  entityVariants/doubleStickyNickel.lua
  entityVariants/justiceHaunt.lua
  entityVariants/lostSoulBaby.lua
  helper_functions.lua
  items/bloodyPenny.lua
  items/goldenHorseshoe.lua
  items/leftHand.lua
  items/playerCard.lua
  items/purpleHeart.lua
  items/swallowedPenny.lua
  main.lua
  modConfigMenu.lua
Labels: addition

#290 Add extra heart on death double
  cards/death.lua
Labels: enhancement

#289 Add doubled effect for the hierophant
  cards/theHierophant.lua
Labels: enhancement

#288 Remove invisible holy shields when continued
  cards/theWorld.lua
  entityVariants/holyShield.lua
  helper_functions.lua
  main.lua
Labels: bug

#286 Persist player data between continued runs
  main.lua
Labels: bug

#285 Double GOOJC is 10 seconds
  cards/getOutOfJail.lua
Labels: enhancement

#284 Drops a finger on the player when using High Priestess in a room with…
  cards/goldBomb.lua
  cards/theHighPriestess.lua
  entityVariants/momsFinger.lua
Labels: enhancement

#283 Fix holy shield getting hit by permacharmed enemies' bullets
  entityVariants/holyShield.lua
Labels: bug

#291 add sfx, fix bug where gapers dont take dmg
  cards/theHighPriestess.lua
  entityVariants/momsFinger.lua
Labels: bug, enhancement

#292 add sfx to judgement spawn
  cards/judgement.lua
Labels: enhancement

#293 add devil black pofo
  cards/theDevil.lua
Labels: enhancement

#294 death black poof
  cards/death.lua
Labels: enhancement

#295 add kerclink sfx to wheel of fortune
  cards/wheelOfFortune.lua
Labels: enhancement

#302 add dusty poof to broken ankh revival + huppys hairball icon
  content/entities2.xml
  entityVariants/hairballPoof.lua
  entityVariants/registry.lua
  helper_functions.lua
  items/brokenAnkh.lua
  items/guppysHairball.lua
  resources/gfx/effects/hairball_poof.anm2
  resources/gfx/effects/hairball_poof.png
Labels: enhancement

#300 jera'd enemies drop red hearts
  cards/jera.lua
Labels: enhancement

#301 Enemies rerolled by ehwaz have 50% hp + the fool opens doors of entered room
  cards/ehwaz.lua
  cards/theFool.lua
Labels: enhancement

#309 Red pill uses null costume to prevent loss on extra animations
  cards/redPill.lua
  content/costumes2.xml
  costumes/registry.lua
  resources/gfx/characters/costumes/costume_002_bookofbelial.png
  resources/gfx/characters/costumes/costume_002_bookofbelial_black.png
  resources/gfx/characters/costumes/costume_002_bookofbelial_blue.png
  resources/gfx/characters/costumes/costume_002_bookofbelial_green.png
  resources/gfx/characters/costumes/costume_002_bookofbelial_grey.png
  resources/gfx/characters/costumes/costume_002_bookofbelial_red.png
  resources/gfx/characters/costumes/costume_002_bookofbelial_white.png
  resources/gfx/characters/costumes_apollyon/costume_002_bookofbelial.png
  resources/gfx/characters/costumes_apollyon/costume_002_bookofbelial_black.png
  resources/gfx/characters/costumes_apollyon/costume_002_bookofbelial_blue.png
  resources/gfx/characters/costumes_apollyon/costume_002_bookofbelial_green.png
  resources/gfx/characters/costumes_apollyon/costume_002_bookofbelial_grey.png
  resources/gfx/characters/costumes_apollyon/costume_002_bookofbelial_red.png
  resources/gfx/characters/costumes_apollyon/costume_002_bookofbelial_white.png
  resources/gfx/characters/costumes_bluebaby/costume_002_bookofbelial.png
  resources/gfx/characters/costumes_forgotten/costume_002_bookofbelial.png
  resources/gfx/characters/costumes_keeper/costume_002_bookofbelial.png
  resources/gfx/characters/costumes_shadow/costume_002_bookofbelial.png
  resources/gfx/characters/redPill.anm2
Labels: bug

#311 Rework The Joker to use states
  cards/joker.lua
  entityVariants/devilHand.lua
Labels: bug

#316 Purple pill now recharges blank card and bc + void
  cards/purplePill.lua
Labels: bug

#315 Fixed pedestal prices staying after buying hermit/devil active item
  cards/theDevil.lua
  cards/theHermit.lua
Labels: bug

#312 Add perthro ignoring starting items
  cards/perthro.lua
  helper_functions.lua
Labels: bug

#317 Add empie costume + functionality
  cards/theEmperor.lua
  content/costumes2.xml
  costumes/registry.lua
  main.lua
  resources/gfx/characters/costumes/costume_emperor.png
  resources/gfx/characters/emperor.anm2
Labels: enhancement

#313 Fix credit card save and continue
  cards/creditCard.lua
  entityVariants/creditCardBaby.lua
  helper_functions.lua
Labels: bug

#323 Fix card weights
  cards/bomb.lua
  cards/butterBean.lua
  cards/diceShard.lua
  cards/fourCents.lua
  cards/joker.lua
  cards/lilBattery.lua
  cards/nickel.lua
  cards/penny.lua
  cards/soulHeart.lua
  cards/threeCents.lua
  cards/twoCents.lua
  entityVariants/devilHand.lua
  resources/gfx/familiars/devil hand.anm2
Labels: bug

#308 Double Black Rune portals spawn in two different positions
  cards/blackRune.lua
Labels: bug

#326 Don't persist global variables between runs
  main.lua
Labels: bug

#327 Implement delay capabilities on double card usage
  cards/perthro.lua
  cards/theStars.lua
  helper_functions.lua
  main.lua
Labels: enhancement

#329 Add sfx cue for counterfeit penny
  content/sounds.xml
  items/counterfeitPenny.lua
  resources/sfx/counterfeit penny.wav
  sounds/registry.lua
Labels: enhancement

#331 Fix tapeworm tear animations
  items/tapeWorm.lua
  resources/gfx/tears/tapeworm tear.anm2
Labels: bug

#330 Create achievements popup for end of challenge unlocks
  challenges/gimmeTheLoot.lua
  helpers/achievements.lua
  main.lua
  resources/gfx/ui/achievements/achievement_holographicloot.png
  resources/gfx/ui/achievements/achievements.anm2
  resources/gfx/ui/achievements/bgblack.png
  resources/gfx/ui/achievements/frame.png
  resources/gfx/ui/achievements/paper.png
  resources/gfx/ui/achievements/paper_plus.png
Labels: addition

#332 Don't use generic "chosen" key for finding random enemies
  cards/goldBomb.lua
  cards/jera.lua
  cards/questionCard.lua
  cards/theHighPriestess.lua
  cards/theTower.lua
  helper_functions.lua
  items/purpleHeart.lua
Labels: bug

#333 Fix card pickup animation queueing finally!!!
  main.lua
Labels: bug

#337 Gold bomb fix
  cards/goldBomb.lua
Labels: bug

#342 New holos
  cards/ansuz.lua
  cards/diceShard.lua
  cards/goldBomb.lua
  cards/theEmperor.lua
  cards/theFool.lua
  cards/theHangedMan.lua
  cards/theHighPriestess.lua
  cards/theLovers.lua
  cards/theMoon.lua
  cards/theSun.lua
  cards/theTower.lua
  helper_functions.lua
Labels: enhancement

#343 fixed dice shard and sun
  cards/diceShard.lua
  cards/theSun.lua
Labels: bug

#348 added the damage_red_hearts flag to tempie
  cards/temperance.lua
  helper_functions.lua
Labels: enhancement

#349 Gimme the Loot now checks if the shop door is locked before unlocking
  challenges/gimmeTheLoot.lua
Labels: bug

#350 GTL: double coins spawned by cards do not convert to loot cards
  items/pokerChip.lua
Labels: bug

#354 Lost soul cool fix
  cards/lostSoul.lua
Labels: bug

#351 Implement latest MCM options and fix save and continue issues
  helper_functions.lua
  main.lua
  modConfigMenu.lua
Labels: bug, addition

#356 Perthro will no longer reroll quest items
  cards/perthro.lua
  helper_functions.lua
Labels: bug

#353 Fix cards not showing when using Loot Deck and blip of card use animation on pickup animation
  cards/registry.lua
  helper_functions.lua
  items/lootDeck.lua
  main.lua
Labels: bug
